// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ra-config
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: ra, ra-context, ra-index

//! Configuration system for ra.
//!
//! ra uses TOML configuration files named `.ra.toml`. Configuration is resolved
//! by walking up the directory tree from the current working directory,
//! collecting any `.ra.toml` files found, then loading `~/.ra.toml` as the
//! global config with lowest precedence.

use std::{
    fmt::{Debug, Display},
    path::{Path, PathBuf},
};

use serde_core::{de::Deserialize, ser::Serialize};

/// Common search parameters shared between search and context commands.
///
/// Both `SearchSettings` and `ContextSettings` implement this trait, allowing
/// shared code for building search parameters from CLI overrides and config
/// defaults.
pub trait SearchDefaults {
    /// Size of the aggregation pool - how many candidates are available for
    /// hierarchical aggregation before elbow cutoff.
    fn aggregation_pool_size(&self) -> usize;

    /// Sibling ratio threshold for hierarchical aggregation.
    fn aggregation_threshold(&self) -> f32;

    /// Score ratio threshold for elbow cutoff (0.0-1.0, lower = more results).
    fn cutoff_ratio(&self) -> f32;

    /// Maximum results to return after aggregation.
    fn limit(&self) -> usize;
}

/// Compiled context rules for file-pattern-based search customization.
///
/// When a file path matches rules, their effects are merged:
/// - **terms**: concatenated from all matching rules
/// - **trees**: intersection (if any rule specifies trees, only the
///   intersection is searched)
/// - **include**: concatenated from all matching rules
#[derive(Debug)]
pub struct CompiledContextRules {/* private fields */}

impl CompiledContextRules {
    /// Compiles context rules from settings.
    pub fn compile(settings: &ContextSettings) -> Result<Self, ConfigError>;

    /// Returns true if no rules are configured.
    pub fn is_empty(&self) -> bool;

    /// Matches a file path against all rules and returns merged results.
    ///
    /// Effects from all matching rules are merged:
    /// - terms: concatenated
    /// - trees: intersected (if any rule specifies trees)
    /// - include: concatenated
    /// - search: first non-None value wins for each field
    pub fn match_rules(&self, path: &Path) -> MatchedRules;

    /// Returns all search terms that match a given file path.
    ///
    /// This is a convenience method that only returns terms.
    pub fn match_terms(&self, path: &Path) -> Vec<String>;
}

/// Compiled glob patterns for efficient file matching.
///
/// Patterns are organized per-tree, allowing quick lookup of whether
/// a file path should be included for indexing in a given tree.
#[derive(Debug)]
pub struct CompiledPatterns {/* private fields */}

impl CompiledPatterns {
    /// Compiles include/exclude patterns from trees into efficient matchers.
    pub fn compile(trees: &[Tree]) -> Result<Self, ConfigError>;

    /// Checks if a path matches the patterns for a given tree.
    ///
    /// A file matches if it matches at least one include pattern
    /// and does not match any exclude pattern.
    ///
    /// The path should be relative to the tree root.
    /// Returns `false` if the tree has no patterns defined.
    pub fn matches(&self, tree: &str, path: &Path) -> bool;

    /// Returns the names of all trees that have patterns.
    pub fn trees(&self) -> impl Iterator<Item = &str>;
}

/// Top-level merged configuration for ra.
///
/// This represents the fully resolved configuration after merging all
/// discovered `.ra.toml` files according to precedence rules.
#[derive(Clone, Debug, Default)]
pub struct Config {
    /// General settings.
    pub settings: Settings,
    /// Search-related settings.
    pub search: SearchSettings,
    /// Context command settings.
    pub context: ContextSettings,
    /// Resolved trees with their absolute paths and patterns.
    pub trees: Vec<Tree>,
    /// Directory containing the most specific config file (determines index
    /// location).
    pub config_root: Option<PathBuf>,
}

impl Config {
    /// Compiles the include/exclude patterns for this configuration.
    ///
    /// Returns a `CompiledPatterns` that can efficiently match file paths
    /// against the configured patterns for each tree.
    pub fn compile_patterns(&self) -> Result<CompiledPatterns, ConfigError>;

    /// Loads configuration by discovering and merging all relevant `.ra.toml`
    /// files.
    ///
    /// This is the main entry point for loading configuration. It:
    /// 1. Discovers all `.ra.toml` files from `cwd` up to the filesystem root
    /// 2. Appends `~/.ra.toml` if it exists
    /// 3. Parses each file
    /// 4. Merges them according to precedence rules (closest to `cwd` wins)
    ///
    /// Returns `Ok(Config::default())` if no configuration files are found.
    pub fn load(cwd: &Path) -> Result<Self, ConfigError>;

    /// Loads configuration from a specific list of config file paths.
    ///
    /// Files should be provided in precedence order: highest precedence first.
    /// This is primarily useful for testing.
    ///
    /// Returns `Ok(Config::default())` if the list is empty.
    pub fn load_from_files(files: &[PathBuf]) -> Result<Self, ConfigError>;

    /// Serializes the effective settings to TOML format.
    ///
    /// This outputs the merged configuration settings in the same format as a
    /// `.ra.toml` file, making it easy to see the effective configuration.
    /// Trees and include patterns are not included since they have resolved
    /// paths and additional metadata.
    pub fn settings_to_toml(&self) -> String;

    /// Validates the configuration and returns any warnings.
    ///
    /// This checks for:
    /// - Tree paths that don't exist or aren't directories
    /// - Include patterns that don't match any files
    /// - Trees that are defined but not referenced by any include pattern
    /// - Include patterns that reference undefined trees
    /// - Empty configuration (no trees defined)
    pub fn validate(&self) -> Vec<ConfigWarning>;
}

/// Errors that can occur when loading or processing configuration.
#[derive(Debug, Display, std::error::Error)]
pub enum ConfigError {
    /// Failed to read a configuration file.
    #[error("failed to read config file {path}: {source}")]
    ReadFile {
        /// Path to the file that could not be read.
        path: PathBuf,
        /// Underlying I/O error.
        source: std::io::Error,
    },
    /// Failed to parse TOML configuration.
    #[error("failed to parse config file {path}: {source}")]
    ParseToml {
        /// Path to the file that could not be parsed.
        path: PathBuf,
        /// Underlying TOML parse error.
        source: toml::de::error::Error,
    },
    /// A tree path does not exist or is not accessible.
    #[error("tree path does not exist: {path}")]
    TreePathNotFound {
        /// The path that was not found.
        path: PathBuf,
    },
    /// A tree path is not a directory.
    #[error("tree path is not a directory: {path}")]
    TreePathNotDirectory {
        /// The path that is not a directory.
        path: PathBuf,
    },
    /// An include pattern references an undefined tree.
    #[error("include pattern references undefined tree: {tree}")]
    UndefinedTree {
        /// Name of the undefined tree.
        tree: String,
    },
    /// Failed to compile a glob pattern.
    #[error("invalid glob pattern '{pattern}': {source}")]
    InvalidPattern {
        /// The invalid pattern.
        pattern: String,
        /// Underlying glob error.
        source: globset::Error,
    },
    /// Failed to determine home directory.
    #[error("could not determine home directory")]
    NoHomeDirectory,
    /// Failed to canonicalize a path.
    #[error("failed to resolve path {path}: {source}")]
    PathResolution {
        /// The path that could not be resolved.
        path: PathBuf,
        /// Underlying I/O error.
        source: std::io::Error,
    },
}

/// A non-fatal warning about the configuration.
#[derive(Clone, Debug, Display, Eq, PartialEq)]
pub enum ConfigWarning {
    /// A tree path does not exist.
    TreePathMissing {
        /// Name of the tree.
        tree: String,
        /// Path that doesn't exist.
        path: String,
    },
    /// A tree path exists but is not a directory.
    TreePathNotDirectory {
        /// Name of the tree.
        tree: String,
        /// Path that is not a directory.
        path: String,
    },
    /// An include pattern doesn't match any files.
    IncludePatternMatchesNothing {
        /// Name of the tree.
        tree: String,
        /// Pattern that matched nothing.
        pattern: String,
    },
    /// No trees are defined.
    NoTreesDefined,
}

/// A resolved context rule.
///
/// Specifies how context search should behave for files matching certain
/// patterns.
#[derive(Clone, Debug)]
pub struct ContextRule {
    /// Glob patterns to match against file paths.
    pub patterns: Vec<String>,
    /// Limit search to these trees (empty means all trees).
    pub trees: Vec<String>,
    /// Additional search terms to inject into the query.
    pub terms: Vec<String>,
    /// Files to always include in results (tree-prefixed paths like
    /// "docs:api/overview.md").
    pub include: Vec<String>,
    /// Search parameter overrides for this rule.
    pub search: Option<SearchOverrides>,
}

/// Settings for the `ra context` command.
///
/// Contains only context-specific term extraction settings. Search parameters
/// are inherited from `SearchSettings` and can be overridden per-rule.
#[derive(Clone, Debug, Default)]
pub struct ContextSettings {
    /// Maximum terms to include in context queries.
    ///
    /// Higher values capture more semantic diversity (locations, characters,
    /// concepts) which is important for prose content where significant terms
    /// may appear infrequently. Default is 50.
    pub terms: usize,
    /// Ignore terms appearing less than this many times in source.
    pub min_term_frequency: usize,
    /// Ignore words shorter than this.
    pub min_word_length: usize,
    /// Ignore words longer than this.
    pub max_word_length: usize,
    /// Maximum bytes to analyze from large files.
    pub sample_size: usize,
    /// Context rules for customizing search behavior per file pattern.
    pub rules: Vec<ContextRule>,
}

/// Field boost configuration for search ranking.
///
/// These weights are applied at query time to control how matches in different
/// fields contribute to the final score.
#[derive(Clone, Copy, Debug, Default)]
pub struct FieldBoosts {
    /// Boost for hierarchy field (document headings).
    pub hierarchy: f32,
    /// Boost for path field (filename matches).
    pub path: f32,
    /// Boost for tags field (frontmatter metadata).
    pub tags: f32,
    /// Boost for body field (document content).
    pub body: f32,
    /// Maximum boost for top-level headings (depth 0-1).
    pub heading_max: f32,
    /// Decay factor per heading level.
    pub heading_decay: f32,
}

impl FieldBoosts {
    /// Computes a depth-based boost for a chunk's heading level.
    ///
    /// - depth 0 (document) and depth 1 (h1) get the maximum boost
    /// - Each subsequent level decays by the decay factor
    ///   - h2 (depth 2): max * decay
    ///   - h3 (depth 3): max * decay²
    ///   - h4 (depth 4): max * decay³
    ///   - etc.
    pub fn heading_boost(&self, depth: u64) -> f32;
}

/// Markdown parser weight configuration for context term extraction.
///
/// These weights control how terms from different heading levels contribute
/// to the context query.
#[derive(Clone, Copy, Debug, Default)]
pub struct MarkdownWeights {
    /// Weight for terms in H1 headings.
    pub h1: f32,
    /// Weight for terms in H2-H3 headings.
    pub h2_h3: f32,
    /// Weight for terms in H4-H6 headings.
    pub h4_h6: f32,
    /// Weight for terms in body text.
    pub body: f32,
}

impl MarkdownWeights {
    /// Returns the source label and weight for a heading level.
    pub fn heading_weight(&self, level: u8) -> (&'static str, f32);
}

/// Result of matching context rules against a file path.
#[derive(Clone, Debug, Default, Serialize)]
pub struct MatchedRules {
    /// Merged terms from all matching rules.
    pub terms: Vec<String>,
    /// Merged tree filter (intersection of all rules' trees; empty means all).
    pub trees: Vec<String>,
    /// Merged include paths from all matching rules.
    pub include: Vec<String>,
    /// Merged search parameter overrides from all matching rules.
    #[serde(skip_serializing_if = "SearchOverrides::is_empty")]
    pub search: SearchOverrides,
}

impl MatchedRules {
    /// Computes effective trees by combining explicit tree filters with
    /// rule-matched trees.
    ///
    /// - If explicit trees are specified, they take precedence (intersected
    ///   with rule trees if any)
    /// - If only rule trees are specified, use those
    /// - If neither is specified, returns empty (meaning all trees)
    pub fn compute_effective_trees(&self, explicit_trees: &[String]) -> Vec<String>;

    /// Returns true if no rules matched.
    pub fn is_empty(&self) -> bool;

    /// Merges another `MatchedRules` into this one.
    ///
    /// - **terms**: concatenated (deduplicated)
    /// - **trees**: intersected (if either specifies trees)
    /// - **include**: concatenated (deduplicated)
    /// - **search**: first non-None value wins for each field
    pub fn merge(&mut self, other: &Self);
}

/// Search parameter overrides that can be specified per context rule.
///
/// All fields are optional; unset fields inherit from `[search]`.
#[derive(Clone, Debug, Default, Serialize)]
pub struct SearchOverrides {
    /// Maximum results to return after aggregation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<usize>,
    /// Size of the aggregation pool - how many candidates are available for
    /// hierarchical aggregation before elbow cutoff.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aggregation_pool_size: Option<usize>,
    /// Score ratio threshold for elbow cutoff (0.0-1.0, lower = more results).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cutoff_ratio: Option<f32>,
    /// Sibling ratio threshold for hierarchical aggregation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aggregation_threshold: Option<f32>,
}

impl SearchOverrides {
    /// Returns true if all fields are None.
    pub fn is_empty(&self) -> bool;
}

/// Search-related settings.
#[derive(Clone, Debug, Default, Deserialize<'de>, Serialize)]
#[serde(default)]
pub struct SearchSettings {
    /// Stemming language.
    pub stemmer: String,
    /// Fuzzy matching Levenshtein distance (0 = disabled).
    pub fuzzy_distance: u8,
    /// Maximum results to return after aggregation.
    pub limit: usize,
    /// Size of the aggregation pool - how many candidates are available for
    /// hierarchical aggregation before elbow cutoff. Larger values allow more
    /// siblings to accumulate, improving aggregation quality.
    #[serde(alias = "max_candidates")]
    pub aggregation_pool_size: usize,
    /// Score ratio threshold for elbow cutoff (0.0-1.0, lower = more results).
    pub cutoff_ratio: f32,
    /// Sibling ratio threshold for hierarchical aggregation.
    pub aggregation_threshold: f32,
    /// Boost multiplier for hierarchy field matches.
    pub boost_hierarchy: f32,
    /// Boost multiplier for path field matches.
    pub boost_path: f32,
    /// Boost multiplier for tags field matches.
    pub boost_tags: f32,
    /// Boost multiplier for body field matches.
    pub boost_body: f32,
    /// Maximum boost for top-level headings (depth 0-1).
    pub boost_heading_max: f32,
    /// Decay factor per heading level (h2 = max * decay, h3 = max * decay²,
    /// etc.).
    pub boost_heading_decay: f32,
    /// Weight for terms extracted from H1 headings.
    pub markdown_h1: f32,
    /// Weight for terms extracted from H2-H3 headings.
    pub markdown_h2_h3: f32,
    /// Weight for terms extracted from H4-H6 headings.
    pub markdown_h4_h6: f32,
    /// Weight for terms extracted from body text.
    pub markdown_body: f32,
}

impl SearchSettings {
    /// Returns the field boost configuration from these settings.
    pub fn field_boosts(&self) -> FieldBoosts;

    /// Returns the markdown parser weight configuration from these settings.
    pub fn markdown_weights(&self) -> MarkdownWeights;
}

impl SearchDefaults for SearchSettings {}

/// General settings for ra.
#[derive(Clone, Debug, Default, Deserialize<'de>, Serialize)]
#[serde(default)]
pub struct Settings {
    /// Maximum results per query.
    pub default_limit: usize,
    /// Relevance multiplier for local (non-global) trees.
    pub local_boost: f32,
    /// Whether to split documents at h1 boundaries.
    pub chunk_at_headings: bool,
    /// Warning threshold for chunk size in characters.
    pub max_chunk_size: usize,
}

/// A named knowledge tree pointing to a directory of documents.
#[derive(Clone, Debug)]
pub struct Tree {
    /// Name of the tree (used in chunk IDs).
    pub name: String,
    /// Resolved absolute path to the tree directory.
    pub path: PathBuf,
    /// Whether this tree was defined in the global `~/.ra.toml`.
    pub is_global: bool,
    /// Include patterns for files to index (defaults to ["**/*.md",
    /// "**/*.txt"]).
    pub include: Vec<String>,
    /// Exclude patterns for files to skip (defaults to empty).
    pub exclude: Vec<String>,
}

/// Discovers all configuration files relevant to the given directory.
///
/// Returns paths in precedence order: closest to `cwd` first, global
/// (`~/.ra.toml`) last. Files closer to `cwd` have higher precedence during
/// merging.
///
/// The function:
/// 1. Walks up from `cwd` to the filesystem root, collecting any `.ra.toml`
///    files found
/// 2. Stops if a config file has `root = true` set
/// 3. Appends `~/.ra.toml` if it exists and no root config was found (lowest
///    precedence)
///
/// Returns an empty vector if no configuration files are found.
pub fn discover_config_files(cwd: &Path) -> Vec<PathBuf>;

/// Formats a path for display, using `~` for home directory or relative paths
/// where appropriate.
///
/// - If `base` is provided and the path is under it, returns a relative path
/// - If the path is under the home directory, replaces the home prefix with `~`
/// - Otherwise returns the path as-is
pub fn format_path_for_display(path: &Path, base: Option<&Path>) -> String;

/// Returns the path to the global configuration file (`~/.ra.toml`).
///
/// Returns `None` if the home directory cannot be determined.
pub fn global_config_path() -> Option<PathBuf>;

/// Returns the global configuration template as a commented-out example.
pub fn global_template() -> String;

/// Checks if a path is the global configuration file.
pub fn is_global_config(path: &Path) -> bool;

/// Returns the local configuration template as a commented-out example.
pub fn local_template() -> String;

/// The configuration filename.
pub const CONFIG_FILENAME: &str = ".ra.toml";

/// Default size of the aggregation pool (SearchSettings.aggregation_pool_size).
///
/// This controls how many candidates are available for hierarchical aggregation
/// before elbow cutoff. A larger pool allows more siblings to accumulate and
/// merge, improving aggregation quality.
///
/// This replaces the old `max_candidates` setting.
pub const DEFAULT_AGGREGATION_POOL_SIZE: usize = 500;

/// Default sibling ratio threshold for aggregation
/// (SearchSettings.aggregation_threshold).
pub const DEFAULT_AGGREGATION_THRESHOLD: f32 = 0.1;

/// Default boost for body field (document content).
pub const DEFAULT_BOOST_BODY: f32 = 1.0;

/// Default decay factor for heading depth boost (each level multiplies by
/// this).
pub const DEFAULT_BOOST_HEADING_DECAY: f32 = 0.7;

/// Default maximum boost for top-level headings (depth 0-1).
pub const DEFAULT_BOOST_HEADING_MAX: f32 = 5.0;

/// Default boost for hierarchy field (matches in document headings).
pub const DEFAULT_BOOST_HIERARCHY: f32 = 3.0;

/// Default boost for path field (filename matches).
pub const DEFAULT_BOOST_PATH: f32 = 12.0;

/// Default boost for tags field (frontmatter metadata).
pub const DEFAULT_BOOST_TAGS: f32 = 5.0;

/// Default setting for splitting documents at headings
/// (Settings.chunk_at_headings).
pub const DEFAULT_CHUNK_AT_HEADINGS: bool = true;

/// Default maximum terms for context queries (ContextSettings.terms).
pub const DEFAULT_CONTEXT_TERMS: usize = 50;

/// Default score ratio threshold for elbow cutoff
/// (SearchSettings.cutoff_ratio).
pub const DEFAULT_CUTOFF_RATIO: f32 = 0.3;

/// Default fuzzy matching distance (SearchSettings.fuzzy_distance).
pub const DEFAULT_FUZZY_DISTANCE: u8 = 1;

/// Default limit for general queries (Settings.default_limit).
pub const DEFAULT_LIMIT: usize = 5;

/// Default relevance multiplier for local trees (Settings.local_boost).
pub const DEFAULT_LOCAL_BOOST: f32 = 1.5;

/// Default weight for terms in body text.
pub const DEFAULT_MARKDOWN_BODY: f32 = 1.0;

/// Default weight for terms in H1 headings.
pub const DEFAULT_MARKDOWN_H1: f32 = 3.0;

/// Default weight for terms in H2-H3 headings.
pub const DEFAULT_MARKDOWN_H2_H3: f32 = 2.0;

/// Default weight for terms in H4-H6 headings.
pub const DEFAULT_MARKDOWN_H4_H6: f32 = 1.5;

/// Default warning threshold for chunk size (Settings.max_chunk_size).
pub const DEFAULT_MAX_CHUNK_SIZE: usize = 50_000;

/// Default maximum word length (ContextSettings.max_word_length).
pub const DEFAULT_MAX_WORD_LENGTH: usize = 30;

/// Default minimum term frequency (ContextSettings.min_term_frequency).
pub const DEFAULT_MIN_TERM_FREQUENCY: usize = 2;

/// Default minimum word length (ContextSettings.min_word_length).
pub const DEFAULT_MIN_WORD_LENGTH: usize = 4;

/// Default sample size for large files (ContextSettings.sample_size).
pub const DEFAULT_SAMPLE_SIZE: usize = 50_000;

/// Default maximum results for search (SearchSettings.limit).
pub const DEFAULT_SEARCH_LIMIT: usize = 10;

/// Default stemming language (SearchSettings.stemmer).
pub const DEFAULT_STEMMER: &str = "english";
