// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ra-context
// Publish: crates.io
// Workspace dependencies: ra-config, ra-document, ra-query
// Workspace dependents: ra, ra-index

//! Context analysis for finding relevant documentation.
//!
//! The `ContextAnalyzer` examines input files and extracts signals used to find
//! related documentation in the knowledge base. It combines three signal types:
//!
//! 1. **Path analysis**: Extract path components as search terms
//! 2. **Pattern matching**: Match file paths against configured glob patterns
//! 3. **Content analysis**: Extract significant terms using keyword extraction
//!
//! These signals are combined into a search query that finds relevant context.
//!
//! ## Keyword Extraction Algorithms
//!
//! Multiple algorithms are available for keyword extraction:
//!
//! - **TextRank** (default): Graph-based ranking similar to PageRank
//! - **TF-IDF**: Corpus-aware ranking using index statistics
//! - **RAKE**: Rapid Automatic Keyword Extraction based on co-occurrence
//! - **YAKE**: Statistical extraction, good for short texts

use std::{
    fmt::{Debug, Display},
    path::Path,
    str::FromStr,
};

use ra_config::{CompiledContextRules, ContextSettings};
use ra_query::QueryExpr;
use serde_core::ser::Serialize;

/// Trait for providing IDF values for terms.
///
/// This abstraction allows the ranking logic to work with different IDF
/// sources, such as a live index or cached values.
pub trait IdfProvider {
    /// Returns the IDF value for a term, or `None` if the term doesn't exist in
    /// the index.
    ///
    /// Higher values indicate rarer terms. Returns `None` for terms that don't
    /// appear in any document, which causes them to be filtered out during
    /// ranking.
    fn idf(&self, term: &str) -> Option<f32>;
}

/// Configuration for context analysis.
#[derive(Clone, Debug, Default)]
pub struct AnalysisConfig {
    /// Maximum number of terms to include in the query.
    pub max_terms: usize,
    /// Minimum term length for extraction.
    pub min_term_length: usize,
    /// Keyword extraction algorithm to use.
    pub algorithm: KeywordAlgorithm,
}

/// Result of analyzing a source file for context.
#[derive(Clone, Debug)]
pub struct ContextAnalysis {
    /// All weighted terms extracted from the file.
    pub terms: Vec<WeightedTerm>,
    /// Ranked terms after scoring (algorithm-dependent).
    pub ranked_terms: Vec<RankedTerm>,
    /// Keywords extracted by the algorithm (unified format).
    pub keywords: Vec<ScoredKeyword>,
    /// The constructed context query (if any terms were extracted).
    pub query: Option<ContextQuery>,
    /// The algorithm used for extraction.
    pub algorithm: KeywordAlgorithm,
}

impl ContextAnalysis {
    /// Returns true if no terms were extracted from the source.
    ///
    /// Note: This checks `terms`, not `keywords`, because keywords may be empty
    /// if the IDF provider filters out all terms (e.g., for TF-IDF with a new
    /// corpus).
    pub fn is_empty(&self) -> bool;

    /// Returns the query expression, if available.
    pub fn query_expr(&self) -> Option<&QueryExpr>;

    /// Returns the human-readable query string, if available.
    pub fn query_string(&self) -> Option<&str>;
}

/// Analyzes files to extract context signals.
pub struct ContextAnalyzer {/* private fields */}

impl ContextAnalyzer {
    /// Analyzes a file and extracts context signals.
    ///
    /// Returns an error if the file cannot be read.
    pub fn analyze_file(&self, path: &Path) -> std::io::Result<ContextSignals>;

    /// Creates a new analyzer with the given settings and rules.
    pub fn new(settings: &ContextSettings, rules: CompiledContextRules) -> Self;

    /// Creates an analyzer with default settings (for testing).
    pub fn with_defaults() -> Self;
}

/// A constructed context query with metadata.
#[derive(Clone, Debug)]
pub struct ContextQuery {
    /// The generated query expression.
    pub expr: QueryExpr,
    /// Human-readable query string for display.
    pub query_string: String,
    /// Terms that were included in the query.
    pub included_terms: Vec<String>,
}

impl ContextQuery {
    /// Returns true if the query is empty (no terms).
    pub fn is_empty(&self) -> bool;

    /// Returns the number of terms in the query.
    pub fn len(&self) -> usize;
}

/// Signals extracted from analyzing a file.
#[derive(Clone, Debug, Default)]
pub struct ContextSignals {
    /// Terms extracted from path components (directories and filename).
    pub path_terms: Vec<String>,
    /// Terms from matching context patterns.
    pub pattern_terms: Vec<String>,
    /// Content sample for MoreLikeThis query (first N bytes).
    pub content_sample: String,
}

impl ContextSignals {
    /// Collects all terms (path + pattern) into a single vector.
    pub fn all_terms(&self) -> Vec<String>;

    /// Returns true if no signals were extracted.
    pub fn is_empty(&self) -> bool;
}

/// Corpus-aware TF-IDF keyword extractor.
///
/// Uses IDF values from an external provider (typically the search index) to
/// rank terms. The score formula is: `frequency × source_weight × idf`.
pub struct CorpusTfIdf<'a, P: IdfProvider> {/* private fields */}

impl<'a, P: IdfProvider> CorpusTfIdf<'a, P> {
    /// Extracts keywords from text using corpus TF-IDF.
    ///
    /// Returns keywords sorted by score (highest first).
    pub fn extract(&self, text: &str) -> Vec<ScoredKeyword>;

    /// Extracts keywords from pre-parsed weighted terms.
    ///
    /// This is useful when terms have already been extracted with structural
    /// weights (e.g., from markdown headings).
    pub fn extract_from_weighted(&self, terms: Vec<WeightedTerm>) -> Vec<ScoredKeyword>;

    /// Creates a new corpus TF-IDF extractor.
    pub fn new(idf_provider: &'a P) -> Self;
}

/// Available keyword extraction algorithms.
#[derive(Clone, Copy, Debug, Default, Display, Eq, FromStr, PartialEq)]
pub enum KeywordAlgorithm {
    /// Corpus-aware TF-IDF using index statistics.
    /// Requires an `IdfProvider` to look up term frequencies across the corpus.
    TfIdf,
    /// RAKE (Rapid Automatic Keyword Extraction).
    /// Extracts key phrases based on word co-occurrence patterns.
    Rake,
    /// TextRank graph-based ranking.
    /// Similar to PageRank, good for extracting representative terms.
    #[default]
    TextRank,
    /// YAKE (Yet Another Keyword Extractor).
    /// Statistical approach using term position, frequency, and context.
    Yake,
}

impl KeywordAlgorithm {
    /// Returns a brief description of the algorithm.
    pub fn description(&self) -> &'static str;
}

/// RAKE (Rapid Automatic Keyword Extraction) extractor.
///
/// Extracts key phrases based on word co-occurrence patterns within the
/// document. Good for technical documentation where phrases matter.
#[derive(Default)]
pub struct RakeExtractor {/* private fields */}

impl RakeExtractor {
    /// Extracts keywords from text using RAKE.
    ///
    /// Returns keywords sorted by score (highest first).
    pub fn extract(&self, text: &str) -> Vec<ScoredKeyword>;

    /// Creates a new RAKE extractor with default stopwords.
    pub fn new() -> Self;
}

/// A term with its computed TF-IDF score.
#[derive(Clone, Debug, Serialize)]
pub struct RankedTerm {
    /// The original weighted term.
    #[serde(flatten)]
    pub term: WeightedTerm,
    /// The IDF value from the index.
    pub idf: f32,
    /// The computed TF-IDF score.
    pub score: f32,
}

impl RankedTerm {
    /// Creates a new ranked term with computed score.
    pub fn new(term: WeightedTerm, idf: f32) -> Self;
}

/// A keyword with its computed score.
#[derive(Clone, Debug, PartialEq)]
pub struct ScoredKeyword {
    /// The extracted keyword or phrase.
    pub term: String,
    /// The relevance score (higher = more relevant).
    pub score: f32,
    /// Optional source label (e.g., "md:h1", "body", "path:filename").
    pub source: Option<String>,
}

impl ScoredKeyword {
    /// Creates a new scored keyword.
    pub fn new(term: impl Into<String>, score: f32) -> Self;

    /// Creates a scored keyword with a source label.
    pub fn with_source(term: impl Into<String>, score: f32, source: impl Into<String>) -> Self;
}

/// A stopword filter combining English and Rust-specific stopwords.
///
/// Uses a `HashSet` for O(1) lookup performance. All words are stored in
/// lowercase for case-insensitive matching.
#[derive(Clone, Default)]
pub struct Stopwords {/* private fields */}

impl Stopwords {
    /// Returns the stopwords as a Vec for use with external libraries.
    pub fn as_vec(&self) -> Vec<String>;

    /// Checks if a term is a stopword.
    ///
    /// The check is case-insensitive for ASCII characters.
    pub fn contains(&self, term: &str) -> bool;

    /// Returns true if no stopwords are configured.
    pub fn is_empty(&self) -> bool;

    /// Returns the total number of stopwords.
    pub fn len(&self) -> usize;

    /// Creates a new stopword filter with default English and Rust stopwords.
    pub fn new() -> Self;
}

/// TextRank graph-based keyword extractor.
///
/// Uses a graph-based ranking algorithm similar to PageRank to find
/// representative terms in the document.
#[derive(Default)]
pub struct TextRankExtractor {/* private fields */}

impl TextRankExtractor {
    /// Extracts keywords from text using TextRank.
    ///
    /// Returns keywords sorted by score (highest first).
    pub fn extract(&self, text: &str) -> Vec<ScoredKeyword>;

    /// Creates a new TextRank extractor with default stopwords and extended
    /// punctuation.
    pub fn new() -> Self;
}

/// A term extracted from a document with associated metadata.
///
/// Terms are the atomic units for building context queries. Each term carries
/// information about where it came from and how often it appeared, which is
/// used for ranking.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct WeightedTerm {
    /// The extracted term (lowercase, filtered).
    pub term: String,
    /// Semantic weight reflecting importance (higher = more relevant).
    pub weight: f32,
    /// Human-readable label for the source (e.g., "path:filename", "md:h1",
    /// "body").
    pub source: String,
    /// How many times this term appeared in the source.
    pub frequency: u32,
}

impl WeightedTerm {
    /// Increments the frequency count.
    pub fn increment(&mut self);

    /// Creates a new weighted term with the given source label and weight.
    pub fn new(term: String, source: impl Into<String>, weight: f32) -> Self;

    /// Computes the raw score for this term (weight * frequency).
    ///
    /// This score does not include IDF adjustment, which is applied later
    /// when ranking against the index.
    pub fn raw_score(&self) -> f32;
}

/// YAKE (Yet Another Keyword Extractor).
///
/// Statistical keyword extraction that considers term position, frequency,
/// and context. Works well on short texts without training.
#[derive(Default)]
pub struct YakeExtractor {/* private fields */}

impl YakeExtractor {
    /// Extracts keywords from text using YAKE.
    ///
    /// Returns keywords sorted by score. Note: YAKE scores are inverted
    /// (lower = more relevant), so we negate them for consistency.
    pub fn extract(&self, text: &str) -> Vec<ScoredKeyword>;

    /// Creates a new YAKE extractor with default stopwords.
    pub fn new() -> Self;
}

/// Analyzes a source file to extract context for finding related documentation.
///
/// This is the main entry point for context analysis. It:
/// 1. Extracts weighted terms from the file path
/// 2. Parses file content (markdown headings get higher weights)
/// 3. Ranks terms using the configured algorithm
/// 4. Constructs a boosted OR query from the top terms
///
/// # Arguments
/// * `path` - Path to the file being analyzed (used for path term extraction)
/// * `content` - Content of the file
/// * `idf_provider` - Source for IDF values (required for TF-IDF, ignored for
///   other algorithms)
/// * `config` - Analysis configuration including algorithm selection
///
/// # Returns
/// A `ContextAnalysis` containing extracted terms, ranked terms, and the query.
pub fn analyze_context<I>(
    path: &Path,
    content: &str,
    idf_provider: &I,
    config: &AnalysisConfig,
) -> ContextAnalysis
where
    I: IdfProvider;

/// Checks if a file is likely binary based on its extension.
pub fn is_binary_file(path: &Path) -> bool;

pub mod keyword {
    //! Keyword extraction algorithms.
    //!
    //! This module provides multiple algorithms for extracting keywords from text:
    //!
    //! - **Corpus TF-IDF**: Uses index-wide statistics to find rare/distinctive
    //!   terms. Best when you have an index and want corpus-aware ranking.
    //! - **RAKE**: Rapid Automatic Keyword Extraction based on word co-occurrence.
    //!   Good for technical documentation.
    //! - **TextRank**: Graph-based ranking similar to PageRank. Good for
    //!   summarization-style extraction.
    //! - **YAKE**: Yet Another Keyword Extractor using statistical features. Good
    //!   for short texts, no training required.

    pub use crate::{
        CorpusTfIdf, KeywordAlgorithm, RakeExtractor, ScoredKeyword, TextRankExtractor,
        YakeExtractor,
    };
}
