// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ra-document
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: ra, ra-context, ra-index
// Unnameable: crate::node::Node

//! Document parsing and chunking for ra.
//!
//! This crate handles parsing markdown and plain text files into hierarchical
//! chunk trees suitable for indexing. It supports:
//! - YAML frontmatter extraction (title, tags)
//! - Hierarchical chunking based on heading structure
//! - GitHub-compatible slug generation for chunk IDs
//! - Hierarchy path generation for search and display

use std::{
    fmt::{Debug, Display},
    hash::Hash,
    path::{Path, PathBuf},
    str::FromStr,
};

use serde_core::de::Deserialize;

/// A chunk identifier in `tree:path#slug` form.
#[derive(Clone, Debug, Display, Eq, FromStr, Hash, PartialEq)]
pub struct ChunkId {
    /// The parent document ID.
    pub doc_id: DocId,
    /// Optional slug for a specific section within the document.
    pub slug: Option<String>,
}

impl ChunkId {
    /// Constructs a chunk ID from tree, path, and optional slug.
    pub fn from_path(tree: &str, path: &Path, slug: Option<&str>) -> Self;

    /// Returns true if this ID refers to a whole document.
    pub fn is_document(&self) -> bool;

    /// Parses a chunk ID from `tree:path#slug` or `tree:path` format.
    pub fn parse(id: &str) -> Result<Self, IdError>;
}

/// A hierarchical tree of nodes representing a parsed document.
///
/// The tree has a single root (the document node) with heading nodes as
/// descendants. Nodes are arranged by heading depth, where each heading becomes
/// a child of the nearest preceding heading with strictly lower depth.
#[derive(Clone, Debug)]
pub struct ChunkTree {/* private fields */}

impl ChunkTree {
    /// Extracts the body text for a node.
    ///
    /// The body is the text within the node's span that is not covered by any
    /// child node's span. For the document node, this is the preamble (content
    /// before the first heading). For heading nodes, this is content after the
    /// heading line minus child spans.
    pub fn body(&self, node: &crate::node::Node) -> &str;

    /// Returns the number of chunks (nodes with non-empty body text).
    pub fn chunk_count(&self) -> usize;

    /// Returns the original document content.
    pub fn content(&self) -> &str;

    /// Extracts all chunks from the tree with their metadata.
    ///
    /// This produces `TreeChunk` structs ready for indexing, including
    /// body text extraction and hierarchy generation.
    ///
    /// All nodes are extracted, including those with empty bodies. This ensures
    /// that document and section titles are searchable even when they have no
    /// direct content (only child sections).
    pub fn extract_chunks(&self, doc_title: &str) -> Vec<TreeChunk>;

    /// Looks up a node by its ID.
    ///
    /// Returns `None` if no node with the given ID exists in the tree.
    pub fn get_node(&self, id: &str) -> Option<&crate::node::Node>;

    /// Checks if a node has non-empty body text (contains non-whitespace).
    pub fn has_body(&self, node: &crate::node::Node) -> bool;

    /// Returns an iterator over all chunks (nodes with non-empty body text).
    ///
    /// A chunk is any node whose body (the span text excluding child spans)
    /// contains non-whitespace characters.
    pub fn iter_chunks(&self) -> impl Iterator<Item = &crate::node::Node>;

    /// Returns an iterator over all nodes in pre-order (depth-first) traversal.
    pub fn iter_preorder(&self) -> impl Iterator<Item = &crate::node::Node>;

    /// Returns the total number of nodes in the tree.
    pub fn node_count(&self) -> usize;

    /// Returns a reference to the root document node.
    pub fn root(&self) -> &crate::node::Node;

    /// Returns a mutable reference to the root document node.
    pub fn root_mut(&mut self) -> &mut crate::node::Node;
}

/// A document identifier in `tree:path` form.
#[derive(Clone, Debug, Display, Eq, FromStr, Hash, PartialEq)]
pub struct DocId {
    /// Name of the tree this document belongs to.
    pub tree: String,
    /// Path relative to the tree root.
    pub path: String,
}

impl DocId {
    /// Constructs a doc ID from a tree name and filesystem path.
    pub fn from_path(tree: &str, path: &Path) -> Self;

    /// Parses a doc ID from `tree:path` format.
    pub fn parse(id: &str) -> Result<Self, IdError>;
}

/// A parsed document ready for indexing.
#[derive(Clone, Debug)]
pub struct Document {
    /// Relative path within the tree.
    pub path: PathBuf,
    /// Name of the tree this document belongs to.
    pub tree: String,
    /// Document title (from frontmatter, first h1, or filename).
    pub title: String,
    /// Tags from frontmatter.
    pub tags: Vec<String>,
    /* private fields */
}

impl Document {
    /// Extracts all chunks from the document's tree, ready for indexing.
    pub fn extract_chunks(&self) -> Vec<TreeChunk>;

    /// Returns the total number of nodes in the document tree.
    pub fn node_count(&self) -> usize;
}

/// Errors that can occur when parsing documents.
#[derive(Debug, Display, std::error::Error)]
pub enum DocumentError {
    /// Failed to read a file.
    #[error("failed to read file {path}: {source}")]
    ReadFile {
        /// Path to the file that could not be read.
        path: PathBuf,
        /// Underlying I/O error.
        source: std::io::Error,
    },
    /// Unsupported file type.
    #[error("unsupported file type: {path}")]
    UnsupportedFileType {
        /// Path to the unsupported file.
        path: PathBuf,
    },
}

/// Parsed frontmatter from a markdown document.
#[derive(Clone, Debug, Default, Deserialize<'de>)]
pub struct Frontmatter {
    /// Document title.
    pub title: Option<String>,
    /// Document tags (supports both array and Obsidian-style inline tags).
    #[serde(default)]
    pub tags: Vec<String>,
}

/// Information about a parsed heading.
#[derive(Clone, Debug)]
pub struct HeadingInfo {
    /// The heading level (1-6 for h1-h6).
    pub level: u8,
    /// The heading text (including inline code).
    pub text: String,
    /// Byte offset where the heading line starts.
    pub heading_start: usize,
    /// Byte offset where the heading line ends.
    pub heading_end: usize,
}

/// Errors that can occur when parsing document or chunk IDs.
#[derive(Clone, Debug, Display, Eq, PartialEq, std::error::Error)]
pub enum IdError {
    /// The input did not match the expected `tree:path[#slug]` format.
    #[error("invalid id format")]
    InvalidFormat,
}

/// Result of parsing a document, including metadata about the parsing process.
#[derive(Clone, Debug)]
pub struct ParseResult {
    /// The parsed document.
    pub document: Document,
}

/// A chunk extracted from the tree, ready for indexing.
///
/// This struct contains all the metadata needed for indexing and search-time
/// aggregation, including the extracted body text.
#[derive(Clone, Debug)]
pub struct TreeChunk {
    /// Globally unique chunk identifier.
    pub id: String,
    /// Document identifier (same for all chunks in a file).
    pub doc_id: String,
    /// Parent node's ID, or None for the document node.
    pub parent_id: Option<String>,
    /// The chunk body text (content within span, excluding child spans).
    pub body: String,
    /// Hierarchy path from document root to this chunk.
    /// Each element is a title in the path. The last element is this chunk's
    /// title. For document nodes, contains just the document title.
    /// For headings, contains [doc_title, ancestor_titles..., this_title].
    pub hierarchy: Vec<String>,
    /// Heading level: 0 for document node, 1-6 for h1-h6.
    pub depth: u8,
    /// Document order index (0-based, pre-order traversal).
    pub position: usize,
    /// Byte offset where this chunk's span starts.
    pub byte_start: usize,
    /// Byte offset where this chunk's span ends (exclusive).
    pub byte_end: usize,
    /// Number of siblings including this chunk.
    pub sibling_count: usize,
}

impl TreeChunk {
    /// Returns the chunk's title (the last element of the hierarchy).
    pub fn title(&self) -> &str;
}

/// Extracts all headings from markdown content with byte offsets for the
/// heading line.
pub fn extract_headings(content: &str) -> Vec<HeadingInfo>;

/// Parses a file from disk, detecting type by extension.
///
/// Supported extensions:
/// - `.md`, `.markdown` - parsed as markdown with hierarchical chunking
/// - `.txt` - parsed as plain text (single document node)
pub fn parse_file(path: &Path, tree: &str) -> Result<ParseResult, DocumentError>;

/// Parses YAML frontmatter from markdown content.
///
/// Returns the parsed frontmatter (if valid) and the remaining content after
/// the frontmatter. If no frontmatter is present or it's malformed, returns
/// `None` and the original content.
///
/// Frontmatter must:
/// - Start at the beginning of the content
/// - Be delimited by `---` on its own line
/// - Contain valid YAML
pub fn parse_frontmatter(content: &str) -> (Option<Frontmatter>, &str);

/// Parses a markdown string into a document.
///
/// # Arguments
/// * `content` - The markdown content to parse
/// * `path` - Relative path within the tree (used for chunk IDs)
/// * `tree` - Name of the tree this document belongs to
pub fn parse_markdown(content: &str, path: &Path, tree: &str) -> ParseResult;

/// Parses a plain text file into a document.
///
/// Text files produce a single document node with the entire file as body.
/// The title is derived from the filename.
pub fn parse_text(content: &str, path: &Path, tree: &str) -> ParseResult;
