// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ra-highlight
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: ra

//! Syntax highlighting and terminal colors for ra.
//!
//! This crate provides utilities for syntax-highlighted output of code and
//! configuration, as well as styled terminal output for headers and status
//! messages.
//!
//! # Terminal Styling
//!
//! The [`Style`] struct provides RGB color support with hex color parsing. Use
//! the semantic theme constants in the [`theme`] module for consistent styling
//! across the application.

use std::{fmt::Debug, ops::Range};

/// A syntax highlighter that can highlight code for terminal output.
#[derive(Default)]
pub struct Highlighter {/* private fields */}

impl Highlighter {
    /// Highlights content with the specified syntax for terminal output.
    ///
    /// If the syntax is not found, returns the content unchanged.
    pub fn highlight(&self, content: &str, syntax_name: &str) -> String;

    /// Creates a new highlighter with the default theme (Dracula).
    pub fn new() -> Self;
}

/// RGB color for terminal output.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Rgb {
    /// Red component (0-255).
    pub r: u8,
    /// Green component (0-255).
    pub g: u8,
    /// Blue component (0-255).
    pub b: u8,
}

impl Rgb {
    /// Parses an RGB color from a hex string (e.g., "#ff5500" or "ff5500").
    ///
    /// Returns `None` if the string is not a valid 6-digit hex color.
    pub fn from_hex(hex: &str) -> Option<Self>;

    /// Creates a new RGB color from components.
    pub const fn new(r: u8, g: u8, b: u8) -> Self;
}

/// Terminal text style with optional foreground color and bold.
#[derive(Clone, Copy, Debug, Default)]
pub struct Style {
    /// Foreground color.
    pub fg: Option<Rgb>,
    /// Whether text should be bold.
    pub bold: bool,
    /// Whether text should be dimmed.
    pub dim: bool,
}

impl Style {
    /// Applies this style to text, returning styled text with ANSI escapes.
    pub fn apply(&self, text: &str) -> String;

    /// Returns this style with bold enabled.
    pub const fn bold(self) -> Self;

    /// Returns this style with dim enabled.
    pub const fn dim(self) -> Self;

    /// Creates a new style with the given foreground color.
    pub const fn fg(color: Rgb) -> Self;

    /// Creates a style from a hex color string.
    ///
    /// # Panics
    /// Panics if the hex string is invalid. Use this only with compile-time
    /// constants.
    pub fn from_hex(hex: &str) -> Self;

    /// Returns the ANSI escape prefix for this style.
    pub fn prefix(&self) -> String;

    /// Returns the ANSI escape suffix to reset styling.
    pub fn suffix(&self) -> &'static str;
}

/// Formats text as a breadcrumb/path.
pub fn breadcrumb(text: &str) -> String;

/// Formats text as content/body text (subtle gray).
pub fn content(text: &str) -> String;

/// Formats text as dimmed/less important.
pub fn dim(text: &str) -> String;

/// Formats text as an error.
pub fn error(text: &str) -> String;

/// Formats content text with indentation and optional match highlighting.
///
/// Applies content styling as the base, with match highlights overlaid.
/// Each line is indented for visual hierarchy under headers.
pub fn format_body(text: &str, match_ranges: &[Range<usize>]) -> String;

/// Formats a header with the theme header style.
pub fn header(text: &str) -> String;

/// Highlights text ranges with the search match style.
pub fn highlight_matches(text: &str, ranges: &[Range<usize>]) -> String;

/// Applies ANSI highlighting to text at the specified byte ranges.
///
/// Inserts the given prefix before each highlighted region and suffix after.
/// Ranges must be valid UTF-8 byte offsets within the text. Overlapping or
/// out-of-order ranges are handled by sorting and merging.
///
/// # Arguments
/// * `text` - The text to highlight
/// * `ranges` - Byte ranges to highlight (must be valid UTF-8 boundaries)
/// * `prefix` - ANSI escape sequence to insert before each highlighted region
/// * `suffix` - ANSI escape sequence to insert after each highlighted region
pub fn highlight_ranges(text: &str, ranges: &[Range<usize>], prefix: &str, suffix: &str) -> String;

/// Indents each line of text with a consistent prefix.
///
/// Uses a visual indent of 3 spaces to offset content from headers.
pub fn indent(text: &str) -> String;

/// Formats and indents content text for display.
///
/// Combines content styling with indentation for clear visual hierarchy.
pub fn indent_content(text: &str) -> String;

/// Returns a dimmed horizontal rule for visual separation.
pub fn rule(width: usize) -> String;

/// Formats text as a subheader (bold).
pub fn subheader(text: &str) -> String;

/// Formats text as a success message.
pub fn success(text: &str) -> String;

/// Formats text as a warning.
pub fn warning(text: &str) -> String;

pub mod theme {
    //! Semantic color theme for terminal output.
    //!
    //! These constants define the visual appearance of different UI elements.
    //! Colors are specified as hex RGB values for modern 24-bit terminal support.

    /// Breadcrumb/path style (purple).
    pub const BREADCRUMB: Style = _;

    /// Content/body text style (soft blue-gray).
    /// Distinguishes document content from metadata while remaining readable.
    pub const CONTENT: Style = _;

    /// Dimmed/secondary text style.
    pub const DIM: Style = _;

    /// Error message style (red).
    pub const ERROR: Style = _;

    /// Header/title style (bold cyan).
    pub const HEADER: Style = _;

    /// Search match highlight style (bold yellow).
    pub const MATCH: Style = _;

    /// Subheader style (bold, no color).
    pub const SUBHEADER: Style = _;

    /// Success message style (green).
    pub const SUCCESS: Style = _;

    /// Warning message style (orange).
    pub const WARNING: Style = _;
}
