// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ra-index
// Publish: crates.io
// Workspace dependencies: ra-config, ra-context, ra-document, ra-query
// Workspace dependents: ra
// Unnameable: crate::search::types::FieldMatch

//! Tantivy-based search index for ra.
//!
//! This crate provides the indexing and search infrastructure for ra's
//! knowledge base. It handles:
//! - Index creation and incremental updates via [`Indexer`]
//! - Full-text search with hierarchical aggregation via [`Searcher`]
//! - Index location resolution based on configuration
//! - Query parsing via [`parse_query`]
//!
//! # Indexing
//!
//! Use [`Indexer`] to build and update the search index:
//!
//! ```ignore
//! use ra_index::{Indexer, SilentReporter};
//!
//! let indexer = Indexer::new(&config)?;
//! let stats = indexer.incremental_update(&mut SilentReporter)?;
//! ```
//!
//! # Searching
//!
//! Use [`Searcher`] or [`open_searcher`] to query the index:
//!
//! ```ignore
//! use ra_index::{open_searcher, SearchParams};
//!
//! let mut searcher = open_searcher(&config)?;
//! let results = searcher.search_aggregated("rust async", &SearchParams::default())?;
//! ```

use std::{
    collections::{HashMap, HashSet},
    fmt::{Debug, Display},
    ops::Range,
    path::{Path, PathBuf},
};

pub use query::{QueryError, QueryErrorKind, QueryExpr, parse as parse_query};
use ra_config::{Config, ContextSettings, FieldBoosts, MatchedRules, Tree};
pub use ra_context::is_binary_file;
use ra_context::{ContextAnalysis, IdfProvider, KeywordAlgorithm};
use ra_query::{QueryError, QueryExpr};
use serde_core::ser::Serialize;
use tantivy::DocAddress;
/// Callback for reporting indexing progress.
pub trait ProgressReporter {
    /// Called when indexing is complete.
    fn on_complete(&mut self, stats: &IndexStats);

    /// Called when a file was successfully indexed.
    fn on_file_done(&mut self, path: &Path, chunks: usize);

    /// Called when a file could not be parsed.
    fn on_file_error(&mut self, path: &Path, error: &str);

    /// Called when a file was removed from the index.
    fn on_file_removed(&mut self, path: &Path);

    /// Called when starting to process a file.
    fn on_file_start(&mut self, path: &Path, current: usize, total: usize);
}

/// Combined analysis results for multiple files.
#[derive(Debug)]
pub struct ContextAnalysisResult {
    /// Per-file analysis results.
    pub files: Vec<FileAnalysis>,
    /// Merged rules across all files.
    pub merged_rules: MatchedRules,
    /// Combined query expression (if any terms were extracted).
    pub query_expr: Option<QueryExpr>,
    /// Warnings encountered while analyzing files.
    pub warnings: Vec<ContextWarning>,
    /// Doc IDs to exclude from results (the input files themselves).
    pub exclude_doc_ids: HashSet<String>,
}

impl ContextAnalysisResult {
    /// Returns true if no useful context was extracted.
    pub fn is_empty(&self) -> bool;

    /// Returns the query string representation, if available.
    pub fn query_string(&self) -> Option<String>;
}

/// Context search engine that encapsulates the full context search flow.
///
/// This struct provides a reusable API for context-based documentation search,
/// suitable for both CLI and MCP service use.
pub struct ContextSearch<'a> {/* private fields */}

impl<'a> ContextSearch<'a> {
    /// Analyzes files and returns combined analysis results.
    ///
    /// This performs the analysis phase without executing the search. Useful
    /// for explain mode or when you need to inspect the analysis before
    /// searching.
    ///
    /// # Arguments
    /// * `files` - Paths to files to analyze
    /// * `explicit_trees` - Tree filter from CLI (empty = all trees)
    ///
    /// # Returns
    /// Combined analysis results including per-file analyses and merged rules.
    pub fn analyze(&self, files: &[&Path], explicit_trees: &[String]) -> ContextAnalysisResult;

    /// Creates a new context search engine.
    ///
    /// # Arguments
    /// * `searcher` - The search index to use for IDF lookups and result
    ///   retrieval
    /// * `context_settings` - Context configuration including rules
    /// * `max_terms` - Maximum number of terms to include in the query
    pub fn new(
        searcher: &'a mut Searcher,
        context_settings: &ContextSettings,
        max_terms: usize,
    ) -> Result<Self, IndexError>;

    /// Executes a context search and returns aggregated results.
    ///
    /// This performs the full context search flow:
    /// 1. Analyze files and extract terms
    /// 2. Build a combined query with rule-injected terms
    /// 3. Execute the search with tree filtering
    /// 4. Inject auto-included files from rules
    ///
    /// # Arguments
    /// * `files` - Paths to files to analyze
    /// * `params` - Search parameters (limit, trees, etc.)
    ///
    /// # Returns
    /// Tuple of (search results, analysis result).
    pub fn search(
        &mut self,
        files: &[&Path],
        params: &SearchParams,
    ) -> Result<(Vec<SearchResult>, ContextAnalysisResult), IndexError>;

    /// Executes a context search using a precomputed analysis result.
    pub fn search_with_analysis(
        &mut self,
        analysis: ContextAnalysisResult,
        params: &SearchParams,
    ) -> Result<(Vec<SearchResult>, ContextAnalysisResult), IndexError>;

    /// Executes a context search and returns pipeline statistics.
    pub fn search_with_analysis_stats(
        &mut self,
        analysis: ContextAnalysisResult,
        params: &SearchParams,
    ) -> Result<(Vec<SearchResult>, ContextAnalysisResult, PipelineStats), IndexError>;

    /// Returns a reference to the underlying searcher.
    pub fn searcher(&self) -> &Searcher;

    /// Creates a new context search engine with a specific keyword extraction
    /// algorithm.
    ///
    /// # Arguments
    /// * `searcher` - The search index to use for IDF lookups and result
    ///   retrieval
    /// * `context_settings` - Context configuration including rules
    /// * `max_terms` - Maximum number of terms to include in the query
    /// * `algorithm` - Keyword extraction algorithm to use
    pub fn with_algorithm(
        searcher: &'a mut Searcher,
        context_settings: &ContextSettings,
        max_terms: usize,
        algorithm: KeywordAlgorithm,
    ) -> Result<Self, IndexError>;
}

/// Warning emitted while analyzing context files.
#[derive(Clone, Debug)]
pub struct ContextWarning {
    /// Path to the file that triggered the warning.
    pub path: String,
    /// Human-readable reason for the warning.
    pub reason: String,
}

/// Reason why the elbow cutoff terminated at a particular point.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub enum ElbowReason {
    /// Ratio between adjacent scores dropped below the threshold.
    RatioBelowThreshold {
        /// The ratio that triggered the cutoff.
        ratio: f32,
        /// The score before the cutoff.
        score_before: f32,
        /// The score after the cutoff.
        score_after: f32,
    },
    /// A zero or negative score was encountered.
    ZeroOrNegativeScore {
        /// The problematic score value.
        score: f32,
    },
    /// No elbow was found; results limited by max_results.
    MaxResultsReached,
    /// Input was empty or had only one element.
    TooFewCandidates,
}

/// Statistics about elbow cutoff processing.
#[derive(Clone, Debug, Serialize)]
pub struct ElbowStats {
    /// Number of candidates before elbow cutoff.
    pub input_count: usize,
    /// Number of candidates after elbow cutoff.
    pub output_count: usize,
    /// Index where cutoff occurred (same as output_count).
    pub elbow_index: usize,
    /// Reason for the cutoff.
    pub reason: ElbowReason,
    /// The cutoff ratio threshold used.
    pub cutoff_ratio: f32,
    /// The max_results limit used.
    pub max_results: usize,
}

/// Analysis result for a single file.
#[derive(Clone, Debug)]
pub struct FileAnalysis {
    /// Path to the analyzed file.
    pub path: String,
    /// Context analysis results (terms, ranked terms, query).
    pub analysis: ContextAnalysis,
    /// Matched rules for this file.
    pub matched_rules: MatchedRules,
}

/// Errors that can occur when working with the search index.
#[derive(Debug, Display, std::error::Error)]
pub enum IndexError {
    /// Failed to open or create the index.
    #[error("failed to open index at {path}: {message}")]
    OpenIndex {
        /// Path to the index directory.
        path: PathBuf,
        /// Error message.
        message: String,
    },
    /// Failed to write to the index.
    #[error("failed to write to index: {0}")]
    Write(String),
    /// Failed to commit changes to the index.
    #[error("failed to commit index: {0}")]
    Commit(String),
    /// I/O error.
    #[error("I/O error: {0}")]
    Io(std::io::Error),
    /// Invalid stemmer language.
    #[error("unsupported stemmer language: {0}")]
    InvalidLanguage(String),
    /// Search query error.
    #[error("{0}")]
    Query(QueryError),
    /// Configuration error.
    #[error("configuration error: {0}")]
    Config(String),
}

impl From<QueryError> for IndexError {}

impl From<std::io::Error> for IndexError {}

/// Statistics from an indexing operation.
#[derive(Clone, Debug, Default)]
pub struct IndexStats {
    /// Number of files processed.
    pub files_processed: usize,
    /// Number of files skipped due to errors.
    pub files_skipped: usize,
    /// Number of chunks indexed.
    pub chunks_indexed: usize,
    /// Number of files added (new).
    pub files_added: usize,
    /// Number of files updated (modified).
    pub files_updated: usize,
    /// Number of files removed.
    pub files_removed: usize,
    /// Errors encountered during parsing (file path, error message).
    pub parse_errors: Vec<(PathBuf, String)>,
}

impl IndexStats {
    /// Returns true if no errors occurred.
    pub fn is_success(&self) -> bool;

    /// Returns the total number of files that changed.
    pub fn total_changes(&self) -> usize;
}

/// Status of the search index.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IndexStatus {
    /// Index exists and matches current configuration.
    Current,
    /// Index exists but configuration has changed (needs full rebuild).
    ConfigChanged,
    /// Index exists but files have changed (needs incremental update).
    Stale,
    /// No index exists.
    Missing,
}

impl IndexStatus {
    /// Returns a human-readable description for display.
    pub fn description(&self) -> &'static str;

    /// Returns true if the index needs a full rebuild (not just incremental).
    pub fn needs_rebuild(&self) -> bool;

    /// Returns true if the index needs any kind of update.
    pub fn needs_update(&self) -> bool;
}

/// Orchestrates the full indexing pipeline.
pub struct Indexer<'a> {/* private fields */}

impl<'a> Indexer<'a> {
    /// Performs a full reindex, ignoring the manifest.
    ///
    /// This deletes all existing index data and reindexes everything from
    /// scratch.
    pub fn full_reindex<R: ProgressReporter>(
        &self,
        reporter: &mut R,
    ) -> Result<IndexStats, IndexError>;

    /// Performs an incremental update, only reindexing changed files.
    pub fn incremental_update<R: ProgressReporter>(
        &self,
        reporter: &mut R,
    ) -> Result<IndexStats, IndexError>;

    /// Returns the path to the index directory.
    pub fn index_dir(&self) -> &Path;

    /// Creates a new indexer for the given configuration.
    ///
    /// Returns an error if the configuration has no config root or patterns
    /// fail to compile.
    pub fn new(config: &'a Config) -> Result<Self, IndexError>;
}

/// Detailed information about how search terms matched a document.
#[derive(Clone, Debug, Default, Serialize)]
pub struct MatchDetails {
    /// Original query terms (before stemming).
    pub original_terms: Vec<String>,
    /// Query terms after stemming/tokenization.
    pub stemmed_terms: Vec<String>,
    /// Map from stemmed query term to indexed terms that matched (including
    /// fuzzy).
    pub term_mappings: HashMap<String, Vec<String>>,
    /// Per-field term matches.
    pub field_matches: HashMap<String, crate::search::types::FieldMatch>,
    /// Base BM25 score returned by Tantivy.
    pub base_score: f32,
    /// Per-field contribution weights.
    pub field_scores: HashMap<String, f32>,
    /// Local boost applied for non-global trees.
    pub local_boost: f32,
    /// Optional Tantivy explanation in pretty JSON.
    pub score_explanation: Option<String>,
}

impl MatchDetails {
    /// Returns true if any match detail was populated.
    pub fn is_populated(&self) -> bool;

    /// Returns the total number of matched terms across all fields.
    pub fn total_matches(&self) -> u32;
}

/// Explanation of a MoreLikeThis query for debugging.
#[derive(Clone, Debug, Serialize)]
pub struct MoreLikeThisExplanation {
    /// ID of the source document.
    pub source_id: String,
    /// Title of the source document.
    pub source_title: String,
    /// Preview of the source document body (first 200 chars).
    pub source_body_preview: String,
    /// Parameters used for the query.
    pub mlt_params: MoreLikeThisParams,
    /// Debug representation of the generated query.
    pub query_repr: String,
}

/// Parameters for MoreLikeThis queries.
///
/// Controls how Tantivy's `MoreLikeThisQuery` extracts and weights terms from
/// the source document to find similar content.
#[derive(Clone, Debug, Default, Serialize)]
pub struct MoreLikeThisParams {
    /// Minimum document frequency for terms. Terms appearing in fewer documents
    /// are ignored.
    pub min_doc_frequency: u64,
    /// Maximum document frequency for terms. Terms appearing in more documents
    /// are ignored.
    pub max_doc_frequency: u64,
    /// Minimum term frequency in the source document. Terms appearing fewer
    /// times are ignored.
    pub min_term_frequency: usize,
    /// Maximum number of query terms to use.
    pub max_query_terms: usize,
    /// Minimum word length. Shorter words are ignored.
    pub min_word_length: usize,
    /// Maximum word length. Longer words are ignored.
    pub max_word_length: usize,
    /// Boost factor applied to terms.
    pub boost_factor: f32,
    /// Stop words to ignore.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub stop_words: Vec<String>,
}

/// Statistics about the search pipeline execution.
///
/// This provides visibility into what happened during each phase of the
/// pipeline, useful for debugging and understanding why certain results were or
/// weren't returned.
#[derive(Clone, Debug, Serialize)]
pub struct PipelineStats {
    /// Number of raw candidates from query execution.
    pub raw_candidate_count: usize,
    /// Number of results after aggregation (before elbow cutoff).
    pub post_aggregation_count: usize,
    /// Number of results after elbow cutoff.
    pub post_elbow_count: usize,
    /// Final number of results after limit applied.
    pub final_count: usize,
    /// Statistics from the elbow cutoff phase.
    pub elbow: ElbowStats,
}

impl PipelineStats {
    /// Creates empty stats for when no query was executed.
    pub fn empty(cutoff_ratio: f32, max_results: usize) -> Self;
}

/// A single search candidate from the index.
///
/// This represents a chunk that matched a search query, with all the metadata
/// needed for display, scoring, and hierarchical aggregation.
#[derive(Clone, Debug, Serialize)]
pub struct SearchCandidate {
    /// Unique chunk identifier: `{tree}:{path}#{slug}` or `{tree}:{path}`.
    pub id: String,
    /// Document identifier: `{tree}:{path}` (same for all chunks in a file).
    pub doc_id: String,
    /// Parent chunk identifier, or None for document nodes.
    pub parent_id: Option<String>,
    /// Hierarchy path from document root to this chunk.
    /// Each element is a title in the path. The last element is this chunk's
    /// title.
    pub hierarchy: Vec<String>,
    /// Heading level: 0 for document node, 1-6 for h1-h6.
    pub depth: u64,
    /// Tree name this chunk belongs to.
    pub tree: String,
    /// File path within the tree.
    pub path: String,
    /// Chunk body content.
    pub body: String,
    /// Document order index (0-based pre-order traversal).
    pub position: u64,
    /// Byte offset where content span starts.
    pub byte_start: u64,
    /// Byte offset where content span ends.
    pub byte_end: u64,
    /// Number of siblings including this node.
    pub sibling_count: u64,
    /// Search relevance score (after boosting).
    pub score: f32,
    /// Optional snippet with query terms highlighted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub snippet: Option<String>,
    /// Byte ranges within `body` where search terms match.
    ///
    /// Offsets are byte positions into the returned `body` text, already sorted
    /// and merged (no overlaps). Each range aligns to a token produced by
    /// the index analyzer after lowercasing/stemming/fuzzy expansion, so
    /// consumers can safely highlight the original substrings using these
    /// offsets.
    #[serde(
        serialize_with = "serialize_ranges",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub match_ranges: Vec<Range<usize>>,
    /// Byte ranges within `hierarchy` (specifically the title, last element)
    /// where search terms match.
    #[serde(
        rename = "title_match_ranges",
        serialize_with = "serialize_ranges",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub hierarchy_match_ranges: Vec<Range<usize>>,
    /// Byte ranges within `path` where search terms match.
    #[serde(
        serialize_with = "serialize_ranges",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub path_match_ranges: Vec<Range<usize>>,
    /// Detailed match information for verbose output.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub match_details: Option<MatchDetails>,
}

impl SearchCandidate {
    /// Returns the breadcrumb string by joining hierarchy elements.
    pub fn breadcrumb(&self) -> String;

    /// Checks if this candidate is an ancestor of another candidate.
    ///
    /// A candidate is an ancestor if:
    /// - They share the same document ID
    /// - AND either:
    ///   - This candidate is the document node (id == doc_id)
    ///   - OR this candidate's slug is a prefix of the other's slug followed by
    ///     `-`
    pub fn is_ancestor_of(&self, other: &Self) -> bool;

    /// Returns the chunk's title (the last element of the hierarchy).
    pub fn title(&self) -> &str;
}

/// Parameters controlling the four-phase search algorithm.
///
/// The search algorithm proceeds in four phases:
/// 1. **Phase 1 (Query)**: Retrieve up to `candidate_limit` matches from the
///    index
/// 2. **Phase 2 (Normalize)**: Normalize scores across trees (multi-tree only)
/// 3. **Phase 3 (Aggregate)**: Aggregate sibling matches using
///    `aggregation_threshold`
/// 4. **Phase 4 (Elbow)**: Apply relevance cutoff using `cutoff_ratio` and
///    `aggregation_pool_size`
/// 5. **Phase 5 (Limit)**: Truncate to final `limit` results
///
/// When `candidate_limit` is not explicitly set, it defaults to `limit * 50` to
/// ensure enough candidates flow through the pipeline for effective
/// aggregation.
#[derive(Clone, Debug, Default, Serialize)]
pub struct SearchParams {
    /// Maximum candidates to retrieve in Phase 1.
    /// If None, derived as `limit * CANDIDATE_LIMIT_MULTIPLIER`.
    pub candidate_limit: Option<usize>,
    /// Score ratio threshold for Phase 4 elbow detection. Default: 0.5.
    pub cutoff_ratio: f32,
    /// Size of the aggregation pool - maximum results after Phase 4 elbow
    /// cutoff.
    ///
    /// This is a buffer for the aggregation algorithm, not a UI limit. Larger
    /// values allow more siblings to accumulate before filtering, improving
    /// aggregation quality. The final `limit` parameter controls what the
    /// user sees.
    pub aggregation_pool_size: usize,
    /// Sibling ratio threshold for Phase 3 aggregation. Default: 0.1.
    pub aggregation_threshold: f32,
    /// Whether to skip Phase 3 aggregation. Default: false.
    pub disable_aggregation: bool,
    /// Final result limit after aggregation. Default: 10.
    pub limit: usize,
    /// Limit results to these trees. If empty, search all trees.
    ///
    /// Note: BM25 scoring uses corpus-wide statistics (document frequency,
    /// average document length) computed across all indexed documents, not
    /// just the filtered trees. This means scores reflect term importance
    /// globally. For most use cases this is acceptable since relative
    /// ranking within results remains meaningful.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub trees: Vec<String>,
    /// Verbosity level for match details (0 = none, 1 = summary, 2+ = full).
    pub verbosity: u8,
}

impl SearchParams {
    /// Returns the effective candidate limit.
    ///
    /// If `candidate_limit` is explicitly set, returns that value.
    /// Otherwise, derives it as `limit * CANDIDATE_LIMIT_MULTIPLIER`.
    pub fn effective_candidate_limit(&self) -> usize;
}

/// A search result, either a single match or an aggregated parent.
///
/// During Phase 3 of the search algorithm, multiple sibling matches may be
/// aggregated into their parent node when enough siblings match. This enum
/// represents both cases:
/// - `Single`: An individual chunk match
/// - `Aggregated`: A parent node that aggregates multiple child matches
#[derive(Clone, Debug, Serialize)]
pub enum SearchResult {
    /// A single chunk match.
    Single(SearchCandidate),
    /// An aggregated parent node with constituent matches.
    Aggregated {
        /// The parent node containing all metadata (id, title, body, score,
        /// etc.)
        parent: SearchCandidate,
        /// The constituent matches that were aggregated.
        constituents: Vec<SearchCandidate>,
    },
}

impl SearchResult {
    /// Creates an aggregated result from a parent node and its constituent
    /// matches.
    ///
    /// The score is computed using Root Sum Square (RSS / L2 norm) of
    /// constituent scores: `score = sqrt(c1² + c2² + ... + cn²)`
    ///
    /// This approach rewards coverage (multiple matching sections) without
    /// letting noise accumulate linearly:
    /// - Two sections scoring 10.0 each → `sqrt(100 + 100) ≈ 14.1` (boosted)
    /// - One strong (20.0) + two weak (2.0) → `sqrt(400 + 4 + 4) ≈ 20.2` (noise
    ///   dampened)
    /// - Single section → unchanged (sqrt of single squared = original)
    pub fn aggregated(parent: SearchCandidate, constituents: Vec<SearchCandidate>) -> Self;

    /// Returns the underlying candidate for this result.
    ///
    /// For `Single` results, returns the matched candidate.
    /// For `Aggregated` results, returns the parent node.
    pub fn candidate(&self) -> &SearchCandidate;

    /// Returns the constituent matches if this is an aggregated result.
    pub fn constituents(&self) -> Option<&[SearchCandidate]>;

    /// Returns true if this is an aggregated result.
    pub fn is_aggregated(&self) -> bool;

    /// Returns match details if available.
    ///
    /// For single results, returns the candidate's match details.
    /// For aggregated results, returns the highest-scoring constituent's
    /// details, which is most likely to have the most comprehensive match
    /// information.
    pub fn match_details(&self) -> Option<&MatchDetails>;

    /// Creates a single result from a candidate.
    pub fn single(candidate: SearchCandidate) -> Self;
}

/// Primary search entry point for the index.
pub struct Searcher {/* private fields */}

impl Searcher {
    /// Computes doc IDs to exclude from results based on input file paths.
    ///
    /// Each input path is canonicalized and compared against tree roots. If a
    /// file is within a configured tree, its doc ID is returned in
    /// `tree:relative_path` format. Relative paths are normalized to
    /// forward slashes.
    pub fn compute_exclude_doc_ids(&self, files: &[&Path]) -> HashSet<String>;

    /// Returns information about the MLT query without executing search.
    ///
    /// This is useful for `--explain` mode to show what terms are extracted
    /// and what the generated query looks like.
    ///
    /// # Arguments
    /// * `id` - The chunk ID to analyze
    /// * `mlt_params` - MoreLikeThis configuration parameters
    ///
    /// # Returns
    /// A tuple of (source document title, extracted terms from the query).
    pub fn explain_more_like_this(
        &self,
        id: &str,
        mlt_params: &MoreLikeThisParams,
    ) -> Result<MoreLikeThisExplanation, IndexError>;

    /// Retrieves a chunk by its exact ID.
    pub fn get_by_id(&self, id: &str) -> Result<Option<SearchCandidate>, IndexError>;

    /// Retrieves all chunks from a document by path.
    pub fn get_by_path(&self, tree: &str, path: &str) -> Result<Vec<SearchCandidate>, IndexError>;

    /// Looks up a document's address by its ID.
    ///
    /// The ID is the unique chunk identifier in the format `tree:path#slug` or
    /// `tree:path`.
    pub fn get_doc_address(&self, id: &str) -> Result<Option<DocAddress>, IndexError>;

    /// Lists all chunks in the index, ordered by ID.
    pub fn list_all(&self) -> Result<Vec<SearchCandidate>, IndexError>;

    /// Returns the number of documents in the index.
    pub fn num_docs(&self) -> Result<u64, IndexError>;

    /// Opens an existing index for searching with default boost values.
    pub fn open(
        path: &Path,
        language: &str,
        trees: &[Tree],
        local_boost: f32,
        fuzzy_distance: u8,
    ) -> Result<Self, IndexError>;

    /// Opens an existing index for searching with custom boost values.
    pub fn open_with_boosts(
        path: &Path,
        language: &str,
        trees: &[Tree],
        local_boost: f32,
        fuzzy_distance: u8,
        boosts: FieldBoosts,
    ) -> Result<Self, IndexError>;

    /// Opens an existing index for searching using configuration.
    pub fn open_with_config(path: &Path, config: &Config) -> Result<Self, IndexError>;

    /// Reads the full content of a chunk by reading the source file span.
    pub fn read_full_content(
        &self,
        tree: &str,
        path: &str,
        byte_start: u64,
        byte_end: u64,
    ) -> Result<String, IndexError>;

    /// Searches using the hierarchical algorithm with per-tree score
    /// normalization.
    pub fn search_aggregated(
        &mut self,
        query_str: &str,
        params: &SearchParams,
    ) -> Result<Vec<SearchResult>, IndexError>;

    /// Searches using a pre-built query expression.
    pub fn search_aggregated_expr(
        &mut self,
        expr: &QueryExpr,
        params: &SearchParams,
    ) -> Result<Vec<SearchResult>, IndexError>;

    /// Searches using a pre-built query expression and returns pipeline
    /// statistics.
    pub fn search_aggregated_expr_with_stats(
        &mut self,
        expr: &QueryExpr,
        params: &SearchParams,
    ) -> Result<(Vec<SearchResult>, PipelineStats), IndexError>;

    /// Searches and returns pipeline statistics along with results.
    pub fn search_aggregated_with_stats(
        &mut self,
        query_str: &str,
        params: &SearchParams,
    ) -> Result<(Vec<SearchResult>, PipelineStats), IndexError>;

    /// Finds documents similar to arbitrary field content.
    pub fn search_more_like_this_by_fields(
        &mut self,
        fields: Vec<(&str, String)>,
        mlt_params: &MoreLikeThisParams,
        search_params: &SearchParams,
        exclude_doc_ids: &HashSet<String>,
    ) -> Result<Vec<SearchResult>, IndexError>;

    /// Finds documents similar to an indexed document by ID.
    pub fn search_more_like_this_by_id(
        &mut self,
        id: &str,
        mlt_params: &MoreLikeThisParams,
        search_params: &SearchParams,
    ) -> Result<Vec<SearchResult>, IndexError>;

    /// Computes the IDF (Inverse Document Frequency) for a term.
    pub fn term_idf(&self, term: &str) -> Result<Option<f32>, IndexError>;

    /// Computes IDF for a term, optionally filtered to specific trees.
    pub fn term_idf_in_trees(
        &self,
        term: &str,
        trees: &[String],
    ) -> Result<Option<f32>, IndexError>;
}

impl IdfProvider for Searcher {}

/// A no-op progress reporter for silent indexing.
pub struct SilentReporter;

impl ProgressReporter for SilentReporter {}

/// A wrapper around `Searcher` that filters IDF lookups to specific trees.
pub struct TreeFilteredSearcher<'a> {/* private fields */}

impl<'a> TreeFilteredSearcher<'a> {
    /// Creates a new tree-filtered searcher.
    pub fn new(searcher: &'a Searcher, trees: Vec<String>) -> Self;
}

impl IdfProvider for TreeFilteredSearcher<'_> {}

/// Determines the current status of the index.
///
/// This checks:
/// 1. Whether the index directory exists
/// 2. Whether the stored config hash matches the current config
///
/// Note: This does NOT check for stale files (that's handled by the manifest).
/// It only checks for Missing and ConfigChanged states.
pub fn detect_index_status(config: &Config) -> IndexStatus;

/// Computes the index directory path based on configuration.
///
/// The index location is determined by the most specific (closest to CWD)
/// `.ra.toml` file:
/// - If a local `.ra.toml` exists, the index is stored in `.ra/index/` sibling
///   to that file
/// - If only `~/.ra.toml` exists, the index is stored in `~/.ra/index/`
/// - If no config exists, returns `None`
///
/// # Arguments
/// * `config` - The loaded configuration. `config_root` should point to the
///   directory containing the highest-precedence config file.
pub fn index_directory(config: &Config) -> Option<PathBuf>;

/// Merges two sets of byte ranges, combining overlapping or adjacent ranges.
///
/// The result is sorted by start position with no overlaps.
pub fn merge_ranges(a: Vec<Range<usize>>, b: Vec<Range<usize>>) -> Vec<Range<usize>>;

/// Creates an index directory path and opens it for searching.
///
/// If `fuzzy_override` is provided, it overrides the config's fuzzy_distance
/// setting.
pub fn open_searcher(config: &Config, fuzzy_override: Option<u8>) -> Result<Searcher, IndexError>;
