// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ra-query
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: ra-context, ra-index
// Unnameable: crate::error::LexError, crate::error::ParseError

//! Query parsing and AST for ra search.
//!
//! This crate provides a query language for searching knowledge bases:
//!
//! - **Terms**: `rust` - words that must appear
//! - **Phrases**: `"error handling"` - exact sequences
//! - **Negation**: `-deprecated` - terms that must NOT appear
//! - **OR**: `rust OR golang` - alternatives
//! - **Grouping**: `(a b) OR (c d)` - precedence control
//! - **Fields**: `title:guide` - search specific fields
//! - **Boosting**: `rust^2.5` - adjust term importance
//!
//! # Example
//!
//! ```
//! use ra_query::parse;
//!
//! let expr = parse("title:guide (rust OR golang) -deprecated").unwrap();
//! assert!(expr.is_some());
//! ```

use std::{
    error::Error,
    fmt::{Debug, Display},
};

/// A unified error type for query parsing.
///
/// This type provides detailed error messages with context, including
/// the original query string and position indicators where applicable.
#[derive(Clone, Debug, Display, Error)]
pub struct QueryError {
    /// The kind of error that occurred.
    pub kind: QueryErrorKind,
    /// The original query string (if available).
    pub query: Option<String>,
}

impl QueryError {
    /// Creates a compile error.
    pub fn compile(message: impl Into<String>) -> Self;

    /// Creates a lex error.
    pub fn lex(message: impl Into<String>, position: usize, query: impl Into<String>) -> Self;

    /// Returns the error message without context.
    pub fn message(&self) -> &str;

    /// Creates a parse error.
    pub fn parse(
        message: impl Into<String>,
        position: Option<usize>,
        query: Option<String>,
    ) -> Self;

    /// Returns a suggestion for common errors.
    pub fn suggestion(&self) -> Option<&'static str>;

    /// Sets the query string for this error.
    pub fn with_query(self, query: impl Into<String>) -> Self;
}

impl From<crate::error::LexError> for QueryError {}

impl From<crate::error::ParseError> for QueryError {}

/// The specific kind of query error.
#[derive(Clone, Debug)]
pub enum QueryErrorKind {
    /// Lexer error (tokenization failed).
    Lex {
        /// Error message.
        message: String,
        /// Byte position in input.
        position: usize,
    },
    /// Parser error (invalid syntax).
    Parse {
        /// Error message.
        message: String,
        /// Approximate byte position in input (if available).
        position: Option<usize>,
    },
    /// Compilation error (invalid semantics).
    Compile {
        /// Error message.
        message: String,
    },
}

/// A parsed query expression.
#[derive(Clone, Debug, Display, PartialEq)]
pub enum QueryExpr {
    /// A single search term.
    Term(String),
    /// An exact phrase (sequence of terms).
    Phrase(Vec<String>),
    /// Negation: results must NOT match this expression.
    Not(Box<Self>),
    /// Conjunction: all sub-expressions must match.
    And(Vec<Self>),
    /// Disjunction: at least one sub-expression must match.
    Or(Vec<Self>),
    /// Field-scoped query: search only within a specific field.
    Field {
        /// Field name (e.g., title, tags, body, path, tree).
        name: String,
        /// Expression to match within that field.
        expr: Box<Self>,
    },
    /// Boosted query: multiplies the score of the inner expression.
    Boost {
        /// The expression to boost.
        expr: Box<Self>,
        /// The boost factor (e.g., 2.5 means 2.5x the normal score).
        factor: f32,
    },
}

impl QueryExpr {
    /// Creates an And expression, flattening nested Ands.
    pub fn and(exprs: Vec<Self>) -> Self;

    /// Creates a boosted expression.
    pub fn boost(expr: Self, factor: f32) -> Self;

    /// Extracts all search terms from the expression.
    ///
    /// This recursively collects all terms and phrase words, which is useful
    /// for highlighting matched terms in search results.
    pub fn extract_terms(&self) -> Vec<String>;

    /// Creates an Or expression, flattening nested Ors.
    pub fn or(exprs: Vec<Self>) -> Self;

    /// Formats the expression as a query string (human-readable form).
    ///
    /// This produces output like: `term^2.5 OR "phrase"^3.0`
    pub fn to_query_string(&self) -> String;
}

/// Parses a query string into an AST.
///
/// Returns `Ok(None)` for empty queries, `Ok(Some(expr))` for valid queries,
/// or `Err(QueryError)` for invalid syntax.
pub fn parse(input: &str) -> Result<Option<QueryExpr>, QueryError>;
