// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ra
// Publish: crates.io
// Binaries: ra
// Workspace dependencies: ra-config, ra-context, ra-document, ra-highlight, ra-index
// Workspace dependents: none

//! ra: Research Assistant
//!
//! A knowledge management system for autonomous coding and writing agents.
//!
//! ra provides structured access to curated knowledge bases for AI agents.
//! Users maintain collections of markdown documents—project-specific and
//! global—that provide context for agent tasks. Because the full corpus may
//! exceed practical context limits, ra indexes these documents and exposes
//! search tools that agents use to retrieve relevant context on demand.
